In [18]:
import numpy as np

A = np.arange(6).reshape(3, 2)
print("A行列 = ")
print(A)
print()
B = np.arange(8).reshape(2, 4)
print("B行列 = ")
print(B)
print()
dot_AB = np.dot(A, B)
print("A･Bの演算結果:")
print(dot_AB)
print()
dot_AB_max = dot_AB.max()
print("A･Bの演算結果要素の最大値:")
print(dot_AB_max)

A行列 = 
[[0 1]
 [2 3]
 [4 5]]

B行列 = 
[[0 1 2 3]
 [4 5 6 7]]

A･Bの演算結果:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]

A･Bの演算結果要素の最大値:
47
